### ISSUE TITLE
long CSV lines are truncated/broken in CSV response from Bernie's services

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/cdaweb-hapi-metadata#2]
curl "https://cdaweb.gsfc.nasa.gov/WS/cdasr/1/dataviews/sp_phys/datasets/AC_H3_CRIS/data/19970827T000000Z,19970905T000000Z/flux_B,flux_C,flux_N,flux_O,flux_F,flux_Ne,flux_Na,flux_Mg,flux_Al,flux_Si,flux_P,flux_S,flux_Cl,flux_Ar,flux_K,flux_Ca,flux_Sc,flux_Ti,flux_V,flux_Cr,flux_Mn,flux_Fe,flux_Co,flux_Ni,cnt_B,cnt_C,cnt_N,cnt_O,cnt_F,cnt_Ne,cnt_Na,cnt_Mg,cnt_Al,cnt_Si,cnt_P,cnt_S,cnt_Cl,cnt_Ar,cnt_K,cnt_Ca,cnt_Sc,cnt_Ti,cnt_V,cnt_Cr,cnt_Mn,cnt_Fe,cnt_Co,cnt_Ni?format=text"

**Comment by rweigel** [comment]
This one gives me

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><DataResult xmlns="http://cdaweb.gsfc.nasa.gov/schema" xmlns:ns2="http://cdf.gsfc.nasa.gov"><FileDescription><Name>https://cdaweb.gsfc.nasa.gov/tmp/wsUipqx9/ac_h3_cris.txt</Name><MimeType>text/plain</MimeType><StartTime>1997-08-27T00:00:00.000Z</StartTime><EndTime>1997-09-05T00:00:00.000Z</EndTime><Length>8182</Length><LastModified>2023-06-19T22:14:58.469Z</LastModified></FileDescription><Status> Please select fewer variables.</Status><Error>Error number:         -360 in listing (wrt_hybd_strct).</Error><Error>Error Message: </Error></DataResult>%
```

Closing b/c no longer using text responses.
